# Config file for most input parameters
# Use this to easily adjust the test parameters based on how the data is written

# The path to the original data (in this case NCAR .netcdf) is stored
# Config file for tests
# Adjust test parameters based on how the data is written

datasets:
  sabl2048b:  # NCAR High Rate
#    name: sabl2048b
    location_paths:
      - /home/idies/workspace/turb/data02_02/ncar-high-rate-fixed-dt/  # Timesteps 0-49
      - /home/idies/workspace/turb/data02_03/ncar-high-rate-fixed-dt/  # Timesteps 50-104. Split due to disk space
    start_timestep: 0
    end_timestep: 104
#  sabl2048b-2:  # NCAR High Rate Timesteps 50-104. Split due to disk space
#    name: sabl2048b
#    location_path: /home/idies/workspace/turb/data02_03/ncar-high-rate-fixed-dt/
#    start_timestep: 50
#    end_timestep: 104
  sabl2048a:  # NCAR Low Rate
#    name: sabl2048a
    location_paths:
      - /home/idies/workspace/turb/data02_02/ncar-low-rate-fixed-dt
    start_timestep: 0
    end_timestep: 19


write_settings:
  desired_zarr_array_length: 512
  desired_zarr_chunk_length: 64
  desired_zarr_compressor: None
  write_mode: prod


general_settings:
  verbose: False
